spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_DURATION}

super:
  admin:
    name: ${SUPER_ADMIN_NAME}
    email: ${SUPER_ADMIN_EMAIL}
    password: ${SUPER_ADMIN_PASSWORD}